//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_tabbed_content
    {
        public long pages_id { get; set; }
        public string data { get; set; }
        public int count { get; set; }
        public int parent_id { get; set; }
    }
}
