//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapi.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YapiContext : DbContext
    {
        public YapiContext()
            : base("name=YapiContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cach> caches { get; set; }
        public virtual DbSet<field_address> field_address { get; set; }
        public virtual DbSet<field_admin_theme> field_admin_theme { get; set; }
        public virtual DbSet<field_body> field_body { get; set; }
        public virtual DbSet<field_category> field_category { get; set; }
        public virtual DbSet<field_date> field_date { get; set; }
        public virtual DbSet<field_email> field_email { get; set; }
        public virtual DbSet<field_event_custom_address> field_event_custom_address { get; set; }
        public virtual DbSet<field_event_date> field_event_date { get; set; }
        public virtual DbSet<field_event_date_details> field_event_date_details { get; set; }
        public virtual DbSet<field_event_date_end> field_event_date_end { get; set; }
        public virtual DbSet<field_event_featured> field_event_featured { get; set; }
        public virtual DbSet<field_event_infinite_boolean> field_event_infinite_boolean { get; set; }
        public virtual DbSet<field_event_registration_link> field_event_registration_link { get; set; }
        public virtual DbSet<field_event_registration_link_custom_text> field_event_registration_link_custom_text { get; set; }
        public virtual DbSet<field_event_repeater_boolean> field_event_repeater_boolean { get; set; }
        public virtual DbSet<field_event_room> field_event_room { get; set; }
        public virtual DbSet<field_external_link> field_external_link { get; set; }
        public virtual DbSet<field_featured_image> field_featured_image { get; set; }
        public virtual DbSet<field_featured_image_cdn> field_featured_image_cdn { get; set; }
        public virtual DbSet<field_featured_quote> field_featured_quote { get; set; }
        public virtual DbSet<field_featured_quote_left> field_featured_quote_left { get; set; }
        public virtual DbSet<field_files> field_files { get; set; }
        public virtual DbSet<field_header_description> field_header_description { get; set; }
        public virtual DbSet<field_header_image> field_header_image { get; set; }
        public virtual DbSet<field_header_img_cdn> field_header_img_cdn { get; set; }
        public virtual DbSet<field_header_img_mobile_offset> field_header_img_mobile_offset { get; set; }
        public virtual DbSet<field_header_title> field_header_title { get; set; }
        public virtual DbSet<field_headline> field_headline { get; set; }
        public virtual DbSet<field_hide_me> field_hide_me { get; set; }
        public virtual DbSet<field_hide_thumbnail_detail> field_hide_thumbnail_detail { get; set; }
        public virtual DbSet<field_home_block> field_home_block { get; set; }
        public virtual DbSet<field_home_featured> field_home_featured { get; set; }
        public virtual DbSet<field_home_topimage_rotation> field_home_topimage_rotation { get; set; }
        public virtual DbSet<field_homepage_background> field_homepage_background { get; set; }
        public virtual DbSet<field_homepage_background_cdn> field_homepage_background_cdn { get; set; }
        public virtual DbSet<field_homepage_text_color> field_homepage_text_color { get; set; }
        public virtual DbSet<field_homepage_transparent_logo> field_homepage_transparent_logo { get; set; }
        public virtual DbSet<field_homepage_transparent_logo_cdn> field_homepage_transparent_logo_cdn { get; set; }
        public virtual DbSet<field_images> field_images { get; set; }
        public virtual DbSet<field_job_title> field_job_title { get; set; }
        public virtual DbSet<field_link> field_link { get; set; }
        public virtual DbSet<field_location> field_location { get; set; }
        public virtual DbSet<field_media_date> field_media_date { get; set; }
        public virtual DbSet<field_media_speaker> field_media_speaker { get; set; }
        public virtual DbSet<field_media_thumbnail> field_media_thumbnail { get; set; }
        public virtual DbSet<field_media_thumbnail_graphic> field_media_thumbnail_graphic { get; set; }
        public virtual DbSet<field_ministry> field_ministry { get; set; }
        public virtual DbSet<field_ministry_website> field_ministry_website { get; set; }
        public virtual DbSet<field_ministry_website_external> field_ministry_website_external { get; set; }
        public virtual DbSet<field_no_sidebar> field_no_sidebar { get; set; }
        public virtual DbSet<field_not_featured_on_homepage> field_not_featured_on_homepage { get; set; }
        public virtual DbSet<field_number_of_events_to_show> field_number_of_events_to_show { get; set; }
        public virtual DbSet<field_pass> field_pass { get; set; }
        public virtual DbSet<field_permissions> field_permissions { get; set; }
        public virtual DbSet<field_person_name> field_person_name { get; set; }
        public virtual DbSet<field_personal_website> field_personal_website { get; set; }
        public virtual DbSet<field_phone> field_phone { get; set; }
        public virtual DbSet<field_process> field_process { get; set; }
        public virtual DbSet<field_publish_from> field_publish_from { get; set; }
        public virtual DbSet<field_publish_until> field_publish_until { get; set; }
        public virtual DbSet<field_redirect_url> field_redirect_url { get; set; }
        public virtual DbSet<field_related_events> field_related_events { get; set; }
        public virtual DbSet<field_related_links> field_related_links { get; set; }
        public virtual DbSet<field_related_links_title> field_related_links_title { get; set; }
        public virtual DbSet<field_resource_links> field_resource_links { get; set; }
        public virtual DbSet<field_resources_title> field_resources_title { get; set; }
        public virtual DbSet<field_roles> field_roles { get; set; }
        public virtual DbSet<field_series_banner_graphic> field_series_banner_graphic { get; set; }
        public virtual DbSet<field_series_date_end> field_series_date_end { get; set; }
        public virtual DbSet<field_series_date_start> field_series_date_start { get; set; }
        public virtual DbSet<field_series_square_graphic> field_series_square_graphic { get; set; }
        public virtual DbSet<field_series_standalone_year> field_series_standalone_year { get; set; }
        public virtual DbSet<field_series_wide_graphic> field_series_wide_graphic { get; set; }
        public virtual DbSet<field_service_contact_name> field_service_contact_name { get; set; }
        public virtual DbSet<field_service_contact_phone> field_service_contact_phone { get; set; }
        public virtual DbSet<field_short_header> field_short_header { get; set; }
        public virtual DbSet<field_show_publish_date> field_show_publish_date { get; set; }
        public virtual DbSet<field_sidebar_content> field_sidebar_content { get; set; }
        public virtual DbSet<field_sort_field> field_sort_field { get; set; }
        public virtual DbSet<field_special_standalone> field_special_standalone { get; set; }
        public virtual DbSet<field_staff_photo> field_staff_photo { get; set; }
        public virtual DbSet<field_staff_sorttitle> field_staff_sorttitle { get; set; }
        public virtual DbSet<field_story_custom_button> field_story_custom_button { get; set; }
        public virtual DbSet<field_story_subtitle> field_story_subtitle { get; set; }
        public virtual DbSet<field_summary> field_summary { get; set; }
        public virtual DbSet<field_tabbed_content> field_tabbed_content { get; set; }
        public virtual DbSet<field_tags> field_tags { get; set; }
        public virtual DbSet<field_thumbnail> field_thumbnail { get; set; }
        public virtual DbSet<field_thumbnail_cdn> field_thumbnail_cdn { get; set; }
        public virtual DbSet<field_title> field_title { get; set; }
        public virtual DbSet<field_video_popup> field_video_popup { get; set; }
        public virtual DbSet<field_youtube_id> field_youtube_id { get; set; }
        public virtual DbSet<fieldgroup> fieldgroups { get; set; }
        public virtual DbSet<fieldgroups_fields> fieldgroups_fields { get; set; }
        public virtual DbSet<field> fields { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<pages_access> pages_access { get; set; }
        public virtual DbSet<pages_parents> pages_parents { get; set; }
        public virtual DbSet<pages_sortfields> pages_sortfields { get; set; }
        public virtual DbSet<process_date_archiver> process_date_archiver { get; set; }
        public virtual DbSet<processredirect> processredirects { get; set; }
        public virtual DbSet<session_login_throttle> session_login_throttle { get; set; }
        public virtual DbSet<template> templates { get; set; }
        public virtual DbSet<textformatter_video_embed> textformatter_video_embed { get; set; }
    }
}
