//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public long id { get; set; }
        public long parent_id { get; set; }
        public long templates_id { get; set; }
        public string name { get; set; }
        public long status { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_users_id { get; set; }
        public System.DateTime created { get; set; }
        public long created_users_id { get; set; }
        public Nullable<System.DateTime> published { get; set; }
        public int sort { get; set; }
    }
}
