//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_date_archiver
    {
        public long id { get; set; }
        public long date_field_id { get; set; }
        public long item_template_id { get; set; }
        public long year_archive_template_id { get; set; }
        public Nullable<long> month_archive_template_id { get; set; }
        public Nullable<long> day_archive_template_id { get; set; }
    }
}
